// Generated by tools/embed_dex.py - do not edit by hand.
//
// Class name and JNI descriptors read from the embedded dex, so the
// loader's reflection lookups cannot drift from the bytes.

#pragma once

static const char kLglMenuClass[] = "com/android/support/Menu";
static const char kLglMenuCtorDesc[] = "(Landroid/content/Context;)V";

// Interaction callback, as this dex declares it.
static const char kLglChangesDesc[] = "(Landroid/content/Context;ILjava/lang/String;IZLjava/lang/String;)V";
static const bool kLglChangesStatic = true;

// Natives this dex declares. A name missing here means this build
// of the menu does not have it, and nothing should assume it does.
static const char *const kLglNatives[] = {
    "Changes",
    "GetFeatureList",
    "Icon",
    "IconWebViewData",
    "Init",
    "SettingsList",
};
static const unsigned int kLglNativeCount = 6;
