// Generated by tools/embed_dex.py - do not edit by hand.
//
// extern "C" declarations matching the embedded dex exactly, plus the
// JNINativeMethod table that binds them.
//
// Why a table instead of plain Java_* symbols: JNI resolves a native by
// name AND descriptor, and it resolves it against the classloader that
// DEFINED the class. The menu class here is defined by our own
// InMemoryDexClassLoader, not by the loader that ran System.loadLibrary,
// so there is nothing for the automatic lookup to find. RegisterNatives
// sidesteps that entirely: we hand ART the (name, descriptor, function)
// triples for the class we just loaded. This is also why the reference
// libraries export only JNI_OnLoad and no Java_* symbols at all.

#pragma once

#include <jni.h>

extern "C" {

// Landroid/content/Context;ILjava/lang/String;IZLjava/lang/String;V
void Changes(JNIEnv *env, jclass clazz, jobject, jint, jobject, jint, jboolean, jobject);

// [Ljava/lang/String;
jarray GetFeatureList(JNIEnv *env, jobject thiz);

// Ljava/lang/String;
jobject Icon(JNIEnv *env, jobject thiz);

// Ljava/lang/String;
jobject IconWebViewData(JNIEnv *env, jobject thiz);

// Landroid/content/Context;Landroid/widget/TextView;Landroid/widget/TextView;V
void Init(JNIEnv *env, jobject thiz, jobject, jobject, jobject);

// [Ljava/lang/String;
jarray SettingsList(JNIEnv *env, jobject thiz);

}  // extern "C"

// Descriptors and function pointers, kept adjacent so the two cannot
// drift apart. Registered in lgl/impl.cpp.
struct LglNativeBinding {
    const char *name;
    const char *descriptor;
    void *function;
};

static const LglNativeBinding kLglNativeBindings[] = {
    {"Changes", "(Landroid/content/Context;ILjava/lang/String;IZLjava/lang/String;)V", reinterpret_cast<void *>(&Changes)},
    {"GetFeatureList", "()[Ljava/lang/String;", reinterpret_cast<void *>(&GetFeatureList)},
    {"Icon", "()Ljava/lang/String;", reinterpret_cast<void *>(&Icon)},
    {"IconWebViewData", "()Ljava/lang/String;", reinterpret_cast<void *>(&IconWebViewData)},
    {"Init", "(Landroid/content/Context;Landroid/widget/TextView;Landroid/widget/TextView;)V", reinterpret_cast<void *>(&Init)},
    {"SettingsList", "()[Ljava/lang/String;", reinterpret_cast<void *>(&SettingsList)},
};
static const unsigned int kLglNativeBindingCount = 6;
